# Generated by Django 3.2.7 on 2021-09-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_pubished_date_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tite',
            new_name='title',
        ),
    ]
