# Generated by Django 3.2.7 on 2021-11-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
